### ISSUE TITLE
Feature Request Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [qinghuzeng/jammming#4]
Awesome job on your feature request. You covered all topics thoroughly and I feel like I have a great understanding of what you want to implement and how you want to do it. Reading your technical design I feel like I could easily code what you described in your doc. I also really like the image to help describe what you are trying to implement. Lastly, nice job adding caveats. It's always great to cover your edge cases and plan for blockers or things that will make it harder to create. All in all, great job on this one and keep up the great work!

**Comment by qinghuzeng** [comment]
Thanks for the comment.
I will keep going and learn those new skills.
